bind -n C-S-Left previous-window
bind -n C-S-Right next-window
# Copy selection to system clipboard using xsel
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -b"

# Paste from system clipboard to tmux buffer
bind-key P run "tmux set-buffer \"$(xsel -o -b)\"; tmux paste-buffer"

run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux

# Rebind the default keys to open new splits in the current directory
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
setw -g mode-keys vi

set -g mouse on

bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xsel -i -p && xsel -o -p | xsel -i -b"

# Optional: Also copy on a simple Enter key if in copy mode
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xsel -i -p && xsel -o -p | xsel -i -b"

bind-key j choose-window 'join-pane -h -s "%%"'

bind-key C-j choose-window 'join-pane -s "%%"'


set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -ga terminal-features "*:sixel"
set -ga update-environment YAZI_IMAGE_BACKEND
