bind -n C-S-Left previous-window
bind -n C-S-Right next-window
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Rebind the default keys to open new splits in the current directory
bind \\ split-window -v -c "#{pane_current_path}"
bind - split-window -h -c "#{pane_current_path}"
:q
:wq
bind c new-window -c "#{pane_current_path}"

set -g mouse on
