bind -n C-S-Left previous-window
bind -n C-S-Right next-window
# Copy selection to system clipboard using xsel
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -b"

# Paste from system clipboard to tmux buffer
bind-key P run "tmux set-buffer \"$(xsel -o -b)\"; tmux paste-buffer"

set -g @plugin 'tmux-plugins/tmux-resurrect'

# Rebind the default keys to open new splits in the current directory
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
setw -g mode-keys vi

set -g mouse on
